# Generated by Django 5.1.1 on 2024-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0003_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_jean_est_malade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
