# Generated by Django 5.1.1 on 2024-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billeterie', '0004_order_total_jean_est_malade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_jean_est_malade',
        ),
    ]
